- id: '1717503146901'
  alias: Anunciar Janela do quarto aberta Automation
  description: ''
  trigger:
    - platform: state
      entity_id:
        - input_button.ativar_alerta_janela_quarto_aberta
  condition: []
  action:
    - service: script.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: script.send_alexa_window_open_announcement
  mode: single