- id: 'ativar_rotina_boa_noite_automation'
  alias: Ativar Rotina Boa Noite
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_boa_noite
      from: 'off'
      to: 'on'
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.boa_noite
  mode: single

- id: 'desativar_flag_rotina_boa_noite_automation'
  alias: Desativar Flag Rotina Boa Noite
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_boa_noite
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
  condition: [ ]
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.flag_ativar_rotina_boa_noite
  mode: single