- id: 'ativar_rotina_ativar_setup_automation'
  alias: Ativar Rotina Iniciar Setup
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_iniciar_setup
      from: 'off'
      to: 'on'
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.iniciar_setup
  mode: single

- id: 'desativar_flag_rotina_ativar_setup_automation'
  alias: Desativar Flag Rotina Iniciar Setup
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_iniciar_setup
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
  condition: [ ]
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.flag_ativar_rotina_iniciar_setup
  mode: single