- id: 'ativar_rotina_hora_da_maldade_automation'
  alias: Ativar Rotina Hora da Maldade
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_hora_da_maldade
      from: 'off'
      to: 'on'
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.hora_da_maldade
  mode: single

- id: 'desativar_flag_rotina_hora_da_maldade_automation'
  alias: Desativar Flag Rotina Hora da Maldade
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_hora_da_maldade
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
  condition: [ ]
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.flag_ativar_rotina_hora_da_maldade
  mode: single