- id: 'ativar_rotina_ate_logo_automation'
  alias: Ativar Rotina Até Logo
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_ate_logo
      from: 'off'
      to: 'on'
  action:
    - service: script.turn_on
      target:
        entity_id: script.ate_logo
  mode: single

- id: 'desativar_flag_rotina_ate_logo_automation'
  alias: Desativar Flag Rotina Até Logo
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_ate_logo
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
  condition: [ ]
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.flag_ativar_rotina_ate_logo
  mode: single