- id: 'ativar_rotina_ligar_setup_automation'
  alias: Ativar Rotina Ligar Setup
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_ligar_setup
      from: 'off'
      to: 'on'
  action:
    - service: script.turn_on
      target:
        entity_id: script.ligar_setup
  mode: single

- id: 'desativar_flag_rotina_ligar_setup_automation'
  alias: Desativar Flag Rotina Ligar Setup
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_ligar_setup
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.flag_ativar_rotina_ligar_setup
  mode: single