- id: 'ligar_luz_banheiro_suite_com_movimento_automation'
  alias: Ligar Luz Banheiro da Suíte com Movimento
  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_presenca_banheiro_suite_occupancy
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: switch.interruptor_do_banheiro_switch_2
      state: 'off'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.interruptor_do_banheiro_switch_2
