- id: '1717675251587'
  alias: Alerta de janela aberta quando ar do quarto estiver ligado
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.tomada_ar_condicionado_do_quarto_power
      above: 100
  condition:
    - condition: state
      entity_id: binary_sensor.sensor_da_janela_do_quarto_pai_door
      state: 'on'
  action:
    - service: script.turn_on
      target:
        entity_id: script.send_alexa_window_open_announcement
  mode: single