- id: ligar_ar_condicionado_escritorio_automation
  alias: 'Ligar Ar Condicionado Escritorio Automation'
  trigger:
    - platform: state
      entity_id:
        - climate.termostato_ar_condicionado_escritorio
      attribute: temperature
  condition: []
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: ' {{ states.climate.termostato_ar_condicionado_escritorio.attributes.temperature  | int == 18 }}'
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.ligarar18
        - conditions:
            - condition: template
              value_template: ' {{ states.climate.termostato_ar_condicionado_escritorio.attributes.temperature  | int == 19 }}'
            - condition: template
              value_template: '{{ states.climate.termostato_ar_condicionado_escritorio.state == "cool" }}'
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.ligarar19
        - conditions:
            - condition: template
              value_template: ' {{ states.climate.termostato_ar_condicionado_escritorio.attributes.temperature  | int == 20 }}'
            - condition: template
              value_template: '{{ states.climate.termostato_ar_condicionado_escritorio.state == "cool" }}'
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.ligarar20
        - conditions:
            - condition: template
              value_template: ' {{ states.climate.termostato_ar_condicionado_escritorio.attributes.temperature  | int == 21 }}'
            - condition: template
              value_template: '{{ states.climate.termostato_ar_condicionado_escritorio.state == "cool" }}'
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.ligarar21
        - conditions:
            - condition: template
              value_template: ' {{ states.climate.termostato_ar_condicionado_escritorio.attributes.temperature  | int == 22 }}'
            - condition: template
              value_template: '{{ states.climate.termostato_ar_condicionado_escritorio.state == "cool" }}'
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.ligarar22
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.flag_ar_condicionado_escritorio_ligado
  mode: single

- id: desligar_ar_condicionado_escritorio_automation
  alias: 'Desligar Ar Condicionado Escritorio Automation'
  trigger:
    - platform: state
      entity_id:
        - climate.termostato_ar_condicionadoo_escritorio
      to: 'off'
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.desligarar
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.flag_ar_condicionado_escritorio_ligado
  mode: single