- id: '1717625353711'
  alias: Desativar Flag Rotina Boa Noite
  description: ''
  trigger:
    - platform: state
      entity_id:
        - input_boolean.flag_ativar_rotina_boa_noite
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
  condition: []
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.flag_ativar_rotina_boa_noite
      data: {}
  mode: single