- id: '1717533412131'
  alias: Ativar Rotina Boa Noite
  description: ''
  trigger:
    - platform: state
      entity_id:
        - input_boolean.ativar_rotina_boa_noite
      from: 'off'
      to: 'on'
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.boa_noite
      data: {}
  mode: single