- id: '1717452454965'
  alias: desligar_ar_condicionado_escritorio_automation
  description: ''
  trigger:
    - platform: state
      entity_id:
        - climate.termostato_ar_condicionado
  condition:
    - condition: template
      value_template: '{{ states(''climate.termostato_ar_condicionado'') == ''off''
      }}'
  action:
    - service: scene.turn_on
      metadata: {}
      target:
        entity_id: scene.desligarar
    - service: input_boolean.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.flag_ar_condicionado_escritorio_ligado
  mode: single