# Loads default set of integrations. Do not remove.
default_config:
  name: JSB-IoT Home Assistant
  unit_system: metric
  currency: BRL
  country: BR
  time_zone: America/Sao_Paulo
  location_name: Home
  language: en
  elevation: 0
  latitude: -16.70618416506013
  longitude: -49.28827285766602
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

automation: !include_dir_merge_list jsb-iot/automations
script: !include_dir_merge_named jsb-iot/scripts
scene: !include_dir_merge_named jsb-iot/scenes
climate: !include_dir_merge_named jsb-iot/climates
emulated_hue: !include_dir_merge_named jsb-iot/hues

input_boolean: !include jsb-iot/helpers/input_boolean.yaml
input_select: !include jsb-iot/helpers/input_select.yaml
input_number: !include jsb-iot/helpers/input_number.yaml
input_text: !include jsb-iot/helpers/input_text.yaml
input_datetime: !include jsb-iot/helpers/input_datetime.yaml
input_button: !include jsb-iot/helpers/input_button.yaml

template:
  sensor:
    - name: "Alexa Selector"
      state: >-
        {% set room = states('input_select.alexa_state') -%}
        {% set echo_select = {
            "Echo Jullia": "echo_jullia",
            "Echo Flex Sala": "echo_flex_sala",
            "Echo Flex Área de serviço": "echo_flex_dispensa",
            "Echo Pai": "echo_pai",
            "Echo Dot Escritório": "echo_dot_escritorio",
            "Echo Hub": "echo_hub",
            "Casa": "casa",
        } %}
        {%- if room in echo_select -%}
          media_player.{{ echo_select.get(room) }}
        {%- endif %}
        
panel_custom:
  - name: devices
    sidebar_title: Devices
    sidebar_icon: mdi:devices
    url_path: devices
    config:
      target: /config/devices/dashboard

  - name: automations
    sidebar_title: Automations
    sidebar_icon: mdi:robot
    url_path: automations
    config:
      target: /config/automation/dashboard

  - name: integrations
    sidebar_title: Integrations
    sidebar_icon: mdi:puzzle
    url_path: integrations
    config:
      target: /config/integrations
