# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

automation: !include_dir_merge_list jsb-iot/automations
script: !include_dir_merge_named jsb-iot/scripts
scene: !include_dir_merge_named jsb-iot/scenes
climate: !include_dir_merge_named jsb-iot/climates

emulated_hue:
  host_ip: !secret ha_ip
  listen_port: 80
  expose_by_default: false
  entities: !include_dir_merge_named jsb-iot/hues

input_boolean: !include jsb-iot/helpers/input_boolean.yaml
input_select: !include jsb-iot/helpers/input_select.yaml
input_number: !include jsb-iot/helpers/input_number.yaml
input_text: !include jsb-iot/helpers/input_text.yaml
input_datetime: !include jsb-iot/helpers/input_datetime.yaml
input_button: !include jsb-iot/helpers/input_button.yaml
