alexa_alertar_janela_quarto_pai_aberta:
  alias: 'Alexa alertar janela do quarto pai aberta (Echo Pai) Script'
  sequence:
    - service: notify.alexa_media
      data:
        target:
          - media_player.echo_pai
        message: A janela do quarto está aberta, por favor, feche a Janela.
        data:
          type: announce
  mode: single