- platform: generic_thermostat
  name: termostato_ar_condicionado_escritorio
  heater: input_boolean.flag_ar_condicionado_escritorio_ligado
  target_sensor: sensor.sensor_temperatura_escritorio_temperature
  ac_mode: true
  min_temp: 18
  max_temp: 22
  target_temp: 20
  cold_tolerance: 0.5
  hot_tolerance: 0.5
  precision: 1